### PR TITLE
assign experimental/private codepoints; leave out MAY algorithms

### LINKED ISSUE #83: Please avoid squatting on codepoints
The draft currently stakes out claims for codepoints in the active range of asymmetric keys, though the values are still in flux.  That seems dangerous.

If we want concrete values for interoperability testing, feel free to use experimental codepoints (100-110) while the draft is still in flux.

We'll stabilize on formal codepoints later in the process once we know what we're getting into.

### PR DESCRIPTION
**Pull request by TJ-91**
fixes #83. this is an alternative to PR #86.

I only assign IDs to "MUST" and "SHOULD" algorithms.
In cases where a referenced ID is not assigned, I write `TBD (Full Algorithm Name)` to keep the reference in tact.

In cases where there are multiple IDs listed and the IDs are only there for convenience and the meaning of the table is still clear, I only write "TBD" to keep the draft more readable. For example in `Table 12: ML-DSA parameters and artifact lengths in octets`.

### CODE REVIEW

**Review by falko-strenzke — CHANGES_REQUESTED** [review]
Thanks for coming up with the solution @TJ-91 and @dkg and this PR. The only thing that I am a bit concerned about right now is that I anticipate that we will rather prioritise SLH-DSA-SHAKE over -SHA2, and thus the meaning of that code point will change again, potentially causing problems during interop testing if one implementation misses to adopt that change. So maybe we wait a bit with the assignment of any code points for SLH-DSA right now?

**Comment by falko-strenzke** [comment]
> We still have codepoints left, so we can just use the next one for SHAKE if it comes to that. I'd be fine with both options.

Yes, I think we can worry about that later.

**Review by falko-strenzke — APPROVED** [review]

**Comment by wussler** [comment]
May sound silly, but what about using 105-109 instead? Most experimental algos I know of are already using 100-102 and this could be a source of conflict

**Comment by falko-strenzke** [comment]
> May sound silly, but what about using 105-109 instead? Most experimental algos I know of are already using 100-102 and this could be a source of conflict

Then that makes sense I think. Clearly, none of these solutions are robust – as soon as anyone else arrives at the same solution there will be a conflict...

**Review by falko-strenzke — APPROVED** [review]

**Review by wussler — APPROVED** [review]
Thank you!

**Comment by dkg** [comment]
Thanks for this, @TJ-91 !  I think this is the right way forward.

**Pull request merged**
